<?xml version="1.0"?>
<!--
	base
	laser:hokuyo
	IMU
-->
<robot name="smartcar_laser" xmlns:xacro="http://www.ros.org/wiki/xacro" >
	<xacro:include filename="$(find mygazebo)/gazebo/mycar_laser_gazebo.urdf.xacro"/>
	<xacro:property name="width" value="0.2" />
  <xacro:property name="leglen" value="0.6" />
  <xacro:property name="polelen" value="0.2" />
  <xacro:property name="bodylen" value="0.6" />
  <xacro:property name="baselen" value="0.4" />
  <xacro:property name="wheeldiam" value="0.04" />
  <xacro:property name="pi" value="3.1415" />

 <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>	
 </xacro:macro>


<xacro:macro name="smartcar_laser" >
<!--  <link name="hokuyo_link">-->
<!--    <visual>-->
<!--      <geometry>-->
<!--        <box size=".1 .1 .2"/>-->
<!--      </geometry>-->
<!--      <material name="white">-->
<!--          <color rgba="1 1 1 1"/>-->
<!--      </material>-->
<!--    </visual>-->
<!--    <collision>-->
<!--      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />-->
<!--      <geometry>-->
<!--      <box size=".12 .12 .1"/>-->
<!--      </geometry>-->
<!--    </collision>-->
<!--    <xacro:default_inertial mass="1"/>-->
<!--  </link>-->

<!--  <joint name="tobox" type="fixed">-->
<!--    <parent link="base_link"/>-->
<!--    <child link="hokuyo_link"/>-->
<!--    <origin xyz="0 -0.15 0.065"/>-->
<!--  </joint>-->
  <link name="hokuyo_link">
    <visual>
      <geometry>
        <box size=".1 .1 .1"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size=".1 .1 .1"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.25"/>
  </link>

  <joint name="tobox" type="fixed">
    <parent link="base_link"/>
    <child link="hokuyo_link"/>
    <origin xyz="${length/2-0.2} 0 0.1"/>
  </joint>
</xacro:macro >
<laser_sim/>
</robot>
