<?xml version="1.0"?>
<!--
	base
	laser:hokuyo
	IMU
-->
<robot name="roadrobotH_base" xmlns:xacro="http://www.ros.org/wiki/xacro" >
	<xacro:include filename="$(find mygazebo)/gazebo/roadrobotH_base_gazebo.xacro"/>
  	<!-- <xacro:include filename="$(find mygazebo)/property/roadrobotH_common_property.xacro"/> -->
    <xacro:include filename="$(find mygazebo)/property/roadrobotH_base_property.xacro"/>



    <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <!-- <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" /> -->

              <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />

    </inertial>
    </xacro:macro>


    <link name="base_link">
        <visual>
            <geometry>
                <box size="${length/1.0} ${width} ${height}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0 0 .8 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${length/1.0} ${width} ${height}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="${robotBodymas}"/>
    </link>

        <link name="medium_link">
        <visual>
            <geometry>
                <box size="${mediumlength} ${mediumwidth} ${mediumheight}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0 0 .8 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${mediumlength} ${mediumwidth} ${mediumheight}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="10"/>
    </link>

    <joint name="medium_base_joint" type="fixed">

        <parent link="base_link"/>
        <child link="medium_link"/>
        <origin rpy=" 0  0  0"  xyz="0 0 ${height/2.0 + mediumheight/2.0}"/>
        <joint_properties damping="1" friction="1"/>
    </joint>

<!-- right_front_leg -->
 <link name="right_front_leg">
        <visual>
            <geometry>
                <cylinder length="${legLen}" radius="${legdiam}"/>
            </geometry>
            <material name="black">
                <color rgba="0 10 5 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${legLen}" radius="${legdiam}"/>
            </geometry>
            <origin  rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="30"/>
    </link>
    <!-- <joint name="right_front_leg_base_joint" type="revolute"> -->
    <joint name="right_front_leg_base_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <parent link="base_link"/>
        <child link="right_front_leg"/>
        <origin rpy=" 0  0  ${pi/2}"  xyz="  ${length/2-0.15} ${width/2-legdiam/2-0.025} ${-legLen/2-height/2-jointgap}"/>
        <limit effort="100" velocity="100" lower="${-2*pi}" upper="${2*pi}"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint>

    <link name="right_front_leg_medium">
        <visual>
            <geometry>
                <cylinder length="${legmediumlen}" radius="${legmediumdiam}"/>
            </geometry>
            <material name="black">
                <color rgba="0 100 50 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${legmediumlen}" radius="${legmediumdiam}"/>
            </geometry>
            <origin  rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="20"/>
    </link>

    <joint name="right_front_medium_leg_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="right_front_leg"/>
        <child link="right_front_leg_medium"/>
        <origin rpy=" ${-pi/2.0}  0  0"  xyz="0 ${-(legdiam/2+legmediumlen/4)} ${-legLen/2.0+legmediumdiam/4}"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint>

    <link name="right_front_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheelLen}" radius="${wheeldiam}"/>
            </geometry>
            <material name="black">
                <color rgba="5 6 7 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheelLen}" radius="${wheeldiam}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${wheelmas}"/>
    </link>

    <joint name="right_front_wheel_joint" type="continuous">
        <axis xyz="0 0 1"/>
        <parent link="right_front_leg_medium"/>
        <child link="right_front_wheel"/>
        <origin rpy="0  0 ${-pi/2.0}"  xyz="0  0 ${(legmediumlen/2+wheelLen/2+jointgap)}"/>
        <limit effort="${wheelJoinLimit_T}" velocity="${wheelJoinLimit_v}"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <!-- test///////////////////////////////////// -->
        <!-- <link name="right_test">
        <visual>
            <geometry>
                <box size="0.3 0.3 0.3"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0 0 .8 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin rpy="0 0 ${pi/2}" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <joint name="right_test_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="right_front_wheel"/>
        <child link="right_test"/>
        <origin rpy=" 0  0  0"  xyz="0 0.2 0"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint> -->
    <!-- test///////////////////////////////////// -->

<!-- right_back_leg -->
 <link name="right_back_leg">
        <visual>
            <geometry>
                <cylinder length="${legLen}" radius="${legdiam}"/>
            </geometry>
            <material name="black">
                <color rgba="0 100 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${legLen}" radius="${legdiam}"/>
            </geometry>
            <origin  rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="30"/>
    </link>

    <joint name="right_back_leg_base_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <parent link="base_link"/>
        <child link="right_back_leg"/>
        <origin rpy=" 0  0  ${pi/2}"  xyz="  ${length/2-0.15} ${-(width/2-legdiam/2-0.025)} ${-legLen/2-height/2-jointgap}"/>
        <limit effort="100" velocity="100" lower="${-2*pi}" upper="${2*pi}"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint>

     <link name="right_back_leg_medium">
        <visual>
            <geometry>
                <cylinder length="${legmediumlen}" radius="${legmediumdiam}"/>
            </geometry>
            <material name="black">
                <color rgba="0 0.5 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${legmediumlen}" radius="${legmediumdiam}"/>
            </geometry>
            <origin  rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="20"/>
    </link>

    <joint name="right_back_medium_leg_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="right_back_leg"/>
        <child link="right_back_leg_medium"/>
         <origin rpy=" ${-pi/2.0}  0  0"  xyz="0 ${-(legdiam/2+legmediumlen/4)} ${-legLen/2.0+legmediumdiam/4}"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint>

    <link name="right_back_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheelLen}" radius="${wheeldiam}"/>
            </geometry>
            <material name="black">
                <color rgba="0.18 0.31 0.31 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheelLen}" radius="${wheeldiam}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${wheelmas}"/>
    </link>

    <joint name="right_back_wheel_joint" type="continuous">
        <axis xyz="0 0 1"/>
        <parent link="right_back_leg_medium"/>
        <child link="right_back_wheel"/>
        <origin rpy="0  0 ${-pi/2.0}"  xyz="0  0 ${(legmediumlen/2+wheelLen/2+jointgap)}"/>
        <limit effort="${wheelJoinLimit_T}" velocity="${wheelJoinLimit_v}"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint> -->
    <!-- test///////////////////////////////////// -->
        <!-- <link name="right_backetest">
        <visual>
            <geometry>
                <box size="0.3 0.3 0.3"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0 .2 .2 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin rpy="0 0 ${pi/2}" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <joint name="right_back_test_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="right_back_wheel"/>
        <child link="right_backetest"/>
        <origin rpy=" 0  0  0"  xyz="0 0.2 0"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint> -->
    <!-- test///////////////////////////////////// -->
<!-- left_front_leg -->
     <link name="left_front_leg">
        <visual>
            <geometry>
                <cylinder length="${legLen}" radius="${legdiam}"/>
            </geometry>
            <material name="black">
                <color rgba="47 79 79 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${legLen}" radius="${legdiam}"/>
            </geometry>
            <origin  rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="30"/>
    </link>

    <joint name="left_front_leg_base_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <parent link="base_link"/>
        <child link="left_front_leg"/>
        <origin rpy=" 0  0  ${pi/2.0}"  xyz="${-(length/2-0.15)} ${(width/2-legdiam/2-0.025)}   ${-legLen/2-height/2-jointgap}"/>
        <limit effort="100" velocity="100" lower="${-2*pi}" upper="${2*pi}"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint>

    <link name="left_front_leg_medium">
        <visual>
            <geometry>
                <cylinder length="${legmediumlen}" radius="${legmediumdiam}"/>
            </geometry>
            <material name="black">
                <color rgba="47 79 79 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${legmediumlen}" radius="${legmediumdiam}"/>
            </geometry>
            <origin  rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="20"/>
    </link>

    <joint name="left_front_medium_leg_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="left_front_leg"/>
        <child link="left_front_leg_medium"/>
        <origin rpy=" ${-pi/2.0}  0  0"  xyz="0 ${(legdiam/2+legmediumlen/4)} ${-legLen/2.0+legmediumdiam/4}"/>
        <joint_properties damping="0.1" friction="0.1"/>
    </joint>

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheelLen}" radius="${wheeldiam}"/>
            </geometry>
            <material name="black">
                <color rgba=".8 0 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheelLen}" radius="${wheeldiam}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${wheelmas}"/>
    </link>

    <joint name="left_front_wheel_joint" type="continuous">
        <axis xyz="0 0 1"/>
        <parent link="left_front_leg_medium"/>
        <child link="left_front_wheel"/>
        <origin rpy="0  0 ${-pi/2.0}"  xyz="0  0 ${-(legmediumlen/2+wheelLen/2+jointgap)}"/>
        <limit effort="${wheelJoinLimit_T}" velocity="${wheelJoinLimit_v}"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>
    <!-- test///////////////////////////////////// -->
        <!-- <link name="left_fronttest">
        <visual>
            <geometry>
                <box size="0.3 0.3 0.3"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0 .2 .2 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin rpy="0 0 ${pi/2}" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <joint name="left_front_test_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="left_front_wheel"/>
        <child link="left_fronttest"/>
        <origin rpy=" 0  0  0"  xyz="0 -0.2 0"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint> -->
    <!-- test///////////////////////////////////// -->
<!-- left_back_leg -->
     <link name="left_back_leg">
        <visual>
            <geometry>
                <cylinder length="${legLen}" radius="${legdiam}"/>
            </geometry>
            <material name="black">
                <color rgba="0 10 10 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${legLen}" radius="${legdiam}"/>
            </geometry>
            <origin  rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="30"/>
    </link>

    <joint name="left_back_leg_base_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <parent link="base_link"/>
        <child link="left_back_leg"/>
        <origin rpy=" 0  0  ${pi/2.0}"  xyz="${-(length/2-0.15)} ${-(width/2-legdiam/2-0.025)}   ${-legLen/2-height/2-jointgap}"/>
        <limit effort="100" velocity="100" lower="${-2*pi}" upper="${2*pi}"/>
        
        <joint_properties damping="0.01" friction="0.01"/>
    </joint>

    <link name="left_back_leg_medium">
        <visual>
            <geometry>
                <cylinder length="${legmediumlen}" radius="${legmediumdiam}"/>
            </geometry>
            <material name="black">
                <color rgba="0 100 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${legmediumlen}" radius="${legmediumdiam}"/>
            </geometry>
            <origin  rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="20"/>
    </link>

    <joint name="left_back_medium_leg_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="left_back_leg"/>
        <child link="left_back_leg_medium"/>
        <origin rpy=" ${-pi/2.0}  0  0"  xyz="0 ${(legdiam/2+legmediumlen/4)} ${-legLen/2.0+legmediumdiam/4}"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint>

    <link name="left_back_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheelLen}" radius="${wheeldiam}"/>
            </geometry>
            <material name="black">
                <color rgba="0.18 0 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheelLen}" radius="${wheeldiam}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${wheelmas}"/>
    </link>

    <joint name="left_back_wheel_joint" type="continuous">
        <axis xyz="0 0 1"/>
        <parent link="left_back_leg_medium"/>
        <child link="left_back_wheel"/>
        <origin rpy="0  0 ${-pi/2.0}"  xyz="0  0 ${-(legmediumlen/2+wheelLen/2+jointgap)}"/>
        <limit effort="${wheelJoinLimit_T}" velocity="${wheelJoinLimit_v}"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>
    <!-- test///////////////////////////////////// -->
        <!-- <link name="left_backtest">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0 .2 .2 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin rpy="0 0 ${pi/2}" xyz="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <joint name="left_back_test_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <parent link="left_back_wheel"/>
        <child link="left_backtest"/>
        <origin rpy=" 0  0  0"  xyz="0 -0.2 0"/>
        <joint_properties damping="0.01" friction="0.01"/>
    </joint> -->
    <!-- test///////////////////////////////////// -->



  <roadrobotH_base_sim/>
  
  <!-- <roadrobotH_common_property/> -->
  <roadrobotH_base_property/>
</robot>
